updated nginx and fixed service scripts

diff --git a/build/nginx/files/http-nginx b/build/nginx/files/http-nginx
--- a/build/nginx/files/http-nginx
+++ b/build/nginx/files/http-nginx
@@ -29,24 +29,59 @@
 
 source /lib/svc/share/smf_include.sh
 
-typeset -r CONF_FILE="/etc/nginx/nginx.conf"
-typeset -r PIDFILE="/var/nginx/nginx.pid"
-typeset -r NGINX="/usr/local/sbin/nginx"
+getproparg() {
+        val=`svcprop -p $1 $SMF_FMRI`
+        [ -n "$val" ] && echo $val
+}
 
-[[ ! -f ${CONF_FILE} ]] && exit $SMF_EXIT_ERR_CONFIG
+check_conf() {
+    if [ ! -f $CONF ]; then
+        echo "Error: nginx/conf file $CONF does not exist"
+        exit $SMF_EXIT_ERR_CONFIG
+    fi
+}
+
+
+CONF=`getproparg nginx/conf`
+NGINX=`getproparg nginx/cmd`
+
+if [ -z $SMF_FMRI ]; then
+    echo "Error: SMF framework variables are not initialized"
+    exit $SMF_EXIT_ERR
+fi
+
+if [ -z $CONF ]; then
+        echo "Error: nginx/conf property not set"
+        exit $SMF_EXIT_ERR_CONFIG
+fi
+
+if [ -z $NGINX ]; then
+        echo "Error: nginx/cmd property not set"
+        exit $SMF_EXIT_ERR_CONFIG
+fi
 
 
 case "$1" in
 start)
-        /bin/rm -f ${PIDFILE}
-        exec ${NGINX} 2>&1
+        check_conf
+        ${NGINX} -c ${CONF}
         ;;
 stop)
-        [[ -f ${PIDFILE} ]] && kill `cat ${PIDFILE}` && exit $SMF_EXIT_OK
-    exit $SMF_EXIT_ERR_FATAL
+        ${NGINX} -c ${CONF} -s stop
+        ;;
+quit)
+        ${NGINX} -c ${CONF} -s quit
+        ;;
+reload)
+        check_conf
+        ${NGINX} -c ${CONF} -s reload
+        ;;
+reopen)
+        check_conf
+        ${NGINX} -c ${CONF} -s reopen
         ;;
 *)
-        print "Usage: $0 {start|stop}"
+        print "Usage: $0 {start|stop|quit|reload|reopen}"
         exit 1
         ;;
 esac
